<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
        <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\MDD4All.FileAccess.Contracts\src\MDD4All.FileAccess.Contracts\MDD4All.FileAccess.Contracts-dev.csproj" />
    </ItemGroup>

</Project>
